"""Convert legacy text prompts into structured desktop interactions."""

from __future__ import annotations

import re
from typing import Any

_OPTION_PATTERN = re.compile(r"\[([^\[\]\r\n]+)\]|【([^【】\r\n]+)】")
_MISSING_VALUES = {"", "-1", "none", "null"}


def _option_description(label: str, question: str) -> str:
    normalized = label.strip().lower()
    if "ai" in normalized or "自动生成" in normalized:
        return "由当前模型根据后续要求生成内容"
    if "手动" in label:
        return "查看、填写或修改内容后继续"
    if normalized in {"yes", "y", "是", "添加", "配图"}:
        return "执行问题中描述的操作"
    if normalized in {"no", "n", "否", "不添加", "不配图"}:
        return "跳过问题中描述的操作"
    if "输入方式" in question:
        return f"使用“{label}”方式继续"
    return "选择此项继续"


def _extract_current_value(question: str) -> str | None:
    match = re.search(
        r"当前(?:值|默认)\s*[:：]\s*(.*?)(?=。(?:如需|可以|请|\[)|\s*\[|$)",
        question,
        re.DOTALL,
    )
    return match.group(1).strip() if match else None


def _extract_context(question: str) -> tuple[str, str]:
    skill_match = re.search(r"技能「([^」]+)」", question)
    parameter_match = re.search(r"参数「([^」]+)」", question)
    skill_name = skill_match.group(1).strip() if skill_match else ""
    parameter_name = parameter_match.group(1).strip() if parameter_match else ""

    if not parameter_name:
        mode_match = re.search(r"(?:知乎)?文章([^：:。]+?)请选择输入方式", question)
        if mode_match:
            parameter_name = f"文章{mode_match.group(1).strip()}"
    if not parameter_name:
        input_match = re.search(r"请输入([^：:。\n（(]+)", question)
        if input_match:
            parameter_name = input_match.group(1).strip()
    return skill_name, parameter_name


def parse_desktop_prompt(
    question: str,
    *,
    title: str = "",
    fields: list[dict[str, Any]] | None = None,
) -> dict[str, Any]:
    """Return UI metadata for a prompt generated by existing skills."""
    question = str(question or "").strip()
    field_defs = [dict(field) for field in (fields or [])]
    primary_field = field_defs[0] if field_defs else {}
    option_labels: list[str] = []

    for match in _OPTION_PATTERN.finditer(question):
        label = (match.group(1) or match.group(2) or "").strip()
        if label and label not in option_labels:
            option_labels.append(label)
    for field in field_defs:
        for item in field.get("options") or []:
            label = str(item.get("label", item.get("value", ""))) if isinstance(item, dict) else str(item)
            if label and label not in option_labels:
                option_labels.append(label)

    current_value = _extract_current_value(question)
    current_is_missing = (
        current_value is None or current_value.strip().lower() in _MISSING_VALUES
    )
    field_required = bool(primary_field.get("required", True))
    field_default = primary_field.get(
        "default_value",
        primary_field.get("default", primary_field.get("value")),
    )
    if field_default is not None:
        field_default = str(field_default)
    default_value = current_value if not current_is_missing else field_default
    skill_name, parameter_name = _extract_context(question)
    asks_for_input = bool(
        field_defs
        or re.search(r"请输入|请描述|请手动输入|不能为空|输入后再继续", question)
    )
    confirms_value = bool(
        re.search(r"请确认技能|沿用当前值|如需修改请输入新值", question)
    )

    if option_labels:
        prompt_type = "choice"
    elif confirms_value and not current_is_missing:
        prompt_type = "confirm_value"
    elif asks_for_input or (confirms_value and current_is_missing):
        prompt_type = "input"
    else:
        prompt_type = "confirmation"

    clean_message = _OPTION_PATTERN.sub("", question)
    clean_message = re.sub(r"\s+", " ", clean_message).strip(" ：:，,。")

    if title:
        display_title = title
    elif prompt_type == "choice":
        display_title = f"选择{parameter_name or '操作方式'}"
    elif prompt_type == "input":
        display_title = f"填写{parameter_name or '所需信息'}"
    elif prompt_type == "confirm_value":
        display_title = f"确认{parameter_name or '参数值'}"
    else:
        display_title = "需要确认"

    options = [
        {
            "id": f"option_{index}",
            "label": label,
            "value": label,
            "description": _option_description(label, question),
        }
        for index, label in enumerate(option_labels)
    ]

    if prompt_type == "choice":
        actions = options
    elif prompt_type == "confirm_value":
        actions = [
            {"id": "keep", "label": "沿用当前值", "value": ""},
            {"id": "replace", "label": "使用新值", "value": None},
        ]
    elif prompt_type == "input":
        actions = [{"id": "submit", "label": "提交并继续", "value": None}]
    else:
        actions = [
            {"id": "approve", "label": "确认执行", "value": "yes"},
            {"id": "reject", "label": "拒绝", "value": None},
        ]

    is_wechat_file_send = "微信" in question and "发送文件" in question
    return {
        "prompt_type": prompt_type,
        "title": display_title,
        "message": clean_message or question,
        "skill_name": skill_name,
        "parameter_name": parameter_name,
        "current_value": None if current_is_missing else current_value,
        "input_label": parameter_name or "输入内容",
        "input_required": prompt_type == "input" and field_required,
        "default_value": default_value,
        "input_placeholder": (
            "输入新值；留空可沿用当前值"
            if prompt_type == "confirm_value"
            else f"请输入{parameter_name or '所需信息'}"
        ),
        "fields": field_defs,
        "options": options,
        "actions": actions,
        "risk_level": (
            "high"
            if is_wechat_file_send
            else ("low" if prompt_type != "confirmation" else "medium")
        ),
    }
